name: Auto Push

on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: fangxx3863/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: https://github.com/yIwIoTT9A21nupT/2aXGmlWs.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:fangxx3863/overwall_backup.git
